spring:
  application:
    name: accommodation-marketplace
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DATASOURCE_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl_auto: update
      properties:
        hibernate:
          format-sql: false

# App Configuration
app:
  jwt:
    secret: ${JWT_SECRET}